name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Configure Git Identity
        run: |
          git config --global user.name "Il Harper"
          git config --global user.email "hi@ilharper.com"
        shell: bash

      - name: Upgrade Make
        run: |
          sudo apt-get install -y --only-upgrade make
        shell: bash

      - name: Setup stgit
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/stacked-git/stgit/releases/download/v2.6.1/stgit_2.6.1-1_amd64.deb
          sudo apt install -y ./stgit_2.6.1-1_amd64.deb
        shell: bash

      - name: Build Package
        run: |
          make ci -j16
        shell: bash

      - uses: actions/upload-artifact@v7
        with:
          name: webview-devtools-mcp-${{ github.sha }}
          path: packages/chrome-devtools-mcp/build/webview-devtools-mcp.tgz
